apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-jeeves
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /events
        pathType: Prefix
        backend:
          service:
            name: event-service
            port:
              number: 8081